[build]
builder = "NIXPACKS"
buildCommand = "npm install"
nixpacksPlan = """
  phases:
    setup:
      nixPkgs:
        - chromium
        - nodejs
"""

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 